version: "3.1"

services:
  postgresql:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      dofus-market-network:

  dofus-market-back:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: runserver 0.0.0.0:80
    volumes:
      - ./django_project:/opt/dofus_market/django_project
      - ./market:/opt/dofus_market/market
      - ./grpc_market:/opt/dofus_market/grpc_market
      - ./api:/opt/dofus_market/api
    ports:
      - "8000:80"
    env_file:
      - ./.env
    environment:
      - POSTGRESQL_HOST=postgresql
    links:
      - postgresql
    networks:
      dofus-market-network:

  dofus-market-grpc:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: grpcrunaioserver --dev
    volumes:
      - ./django_project:/opt/dofus_market/django_project
      - ./market:/opt/dofus_market/market
      - ./grpc_market:/opt/dofus_market/grpc_market
      - ./api:/opt/dofus_market/api
    ports:
      - "50051:50051"
    env_file:
      - ./.env
    environment:
      - POSTGRESQL_HOST=postgresql
    links:
      - postgresql
    networks:
      dofus-market-network:

  envoy:
    image: envoyproxy/envoy:v1.28.0
    volumes:
      - ./deploy/envoy:/etc/envoy
    ports:
      - "9001:9001"
    links:
      - dofus-market-grpc
    networks:
      dofus-market-network:

networks:
  dofus-market-network:
