# Generated by Django 5.0.6 on 2024-06-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('_prix_ra', models.IntegerField()),
                ('_prix_pa', models.IntegerField()),
                ('_prix_ba', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DofusObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('effects', models.ManyToManyField(to='market.caracteristique')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientForCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dofus_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.dofusobject')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dofusobject',
            name='ingredients',
            field=models.ManyToManyField(through='market.IngredientForCraft', to='market.ingredient'),
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='rune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.rune'),
        ),
    ]
