# Generated by Django 5.0.6 on 2024-06-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('level', models.IntegerField()),
                ('number_of_ra', models.FloatField(default=0.0)),
                ('number_of_pa', models.FloatField(default=0.0)),
                ('number_of_ba', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=1000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prix_ra', models.IntegerField(default=0)),
                ('prix_pa', models.IntegerField(default=0)),
                ('prix_ba', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientForCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DofusObject',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('_effects', models.ManyToManyField(to='market.caracteristique')),
                ('_ingredients', models.ManyToManyField(to='market.ingredientforcraft')),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.metier')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristique',
            name='rune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.rune'),
        ),
    ]
