# Generated by Django 5.0.6 on 2024-06-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dofusobject',
            old_name='effects',
            new_name='_effects',
        ),
        migrations.RenameField(
            model_name='dofusobject',
            old_name='ingredients',
            new_name='_ingredients',
        ),
    ]
