# Generated by Django 5.0.6 on 2024-06-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='market.ingredient')),
                ('level', models.IntegerField(default=0)),
                ('ingredients', models.ManyToManyField(to='market.ingredientforcraft')),
            ],
        ),
    ]
