# Generated by Django 5.0.6 on 2024-06-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_effects_dofusobject__effects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rune',
            old_name='_prix_ba',
            new_name='prix_ba',
        ),
        migrations.RenameField(
            model_name='rune',
            old_name='_prix_pa',
            new_name='prix_pa',
        ),
        migrations.RenameField(
            model_name='rune',
            old_name='_prix_ra',
            new_name='prix_ra',
        ),
    ]
