# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_market.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_market.proto\x12\x18\x64ofus_market.grpc_market\x1a\x1bgoogle/protobuf/empty.proto\"(\n\x18IngredientDestroyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\x15IngredientListRequest\"W\n\x16IngredientListResponse\x12=\n\x07results\x18\x01 \x03(\x0b\x32,.dofus_market.grpc_market.IngredientResponse\"l\n\x1eIngredientPartialUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x16_partial_update_fields\x18\x02 \x03(\t\x12\x12\n\x05price\x18\x03 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_price\"?\n\x11IngredientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x05price\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_price\"@\n\x12IngredientResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x05price\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_price\")\n\x19IngredientRetrieveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2\x96\x05\n\x14IngredientController\x12\x65\n\x06\x43reate\x12+.dofus_market.grpc_market.IngredientRequest\x1a,.dofus_market.grpc_market.IngredientResponse\"\x00\x12W\n\x07\x44\x65stroy\x12\x32.dofus_market.grpc_market.IngredientDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12k\n\x04List\x12/.dofus_market.grpc_market.IngredientListRequest\x1a\x30.dofus_market.grpc_market.IngredientListResponse\"\x00\x12y\n\rPartialUpdate\x12\x38.dofus_market.grpc_market.IngredientPartialUpdateRequest\x1a,.dofus_market.grpc_market.IngredientResponse\"\x00\x12o\n\x08Retrieve\x12\x33.dofus_market.grpc_market.IngredientRetrieveRequest\x1a,.dofus_market.grpc_market.IngredientResponse\"\x00\x12\x65\n\x06Update\x12+.dofus_market.grpc_market.IngredientRequest\x1a,.dofus_market.grpc_market.IngredientResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGREDIENTDESTROYREQUEST']._serialized_start=76
  _globals['_INGREDIENTDESTROYREQUEST']._serialized_end=116
  _globals['_INGREDIENTLISTREQUEST']._serialized_start=118
  _globals['_INGREDIENTLISTREQUEST']._serialized_end=141
  _globals['_INGREDIENTLISTRESPONSE']._serialized_start=143
  _globals['_INGREDIENTLISTRESPONSE']._serialized_end=230
  _globals['_INGREDIENTPARTIALUPDATEREQUEST']._serialized_start=232
  _globals['_INGREDIENTPARTIALUPDATEREQUEST']._serialized_end=340
  _globals['_INGREDIENTREQUEST']._serialized_start=342
  _globals['_INGREDIENTREQUEST']._serialized_end=405
  _globals['_INGREDIENTRESPONSE']._serialized_start=407
  _globals['_INGREDIENTRESPONSE']._serialized_end=471
  _globals['_INGREDIENTRETRIEVEREQUEST']._serialized_start=473
  _globals['_INGREDIENTRETRIEVEREQUEST']._serialized_end=514
  _globals['_INGREDIENTCONTROLLER']._serialized_start=517
  _globals['_INGREDIENTCONTROLLER']._serialized_end=1179
# @@protoc_insertion_point(module_scope)
