apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: {{ .Values.serviceName }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: {{ .Values.serviceName }}-frontend