name: Django Tests

on:
  push:
    branches:
      - main
      - 2-move-to-django-socio-grpc-framework

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

        with:
          python-version: "3.12" # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          cd backend && poetry install --with tests --no-interaction

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgres://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV
          echo "POSTGRESQL_DB_NAME=test_db" >> $GITHUB_ENV
          echo "POSTGRESQL_USER=test_user" >> $GITHUB_ENV
          echo "POSTGRESQL_PASSWORD=test_password" >> $GITHUB_ENV
          echo "POSTGRESQL_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRESQL_PORT=5432" >> $GITHUB_ENV

      - name: Run Django tests
        run: |
          cd backend && poetry run pytest

      - name: Upload test results
        uses: actions/upload-artifact@v4

        with:
          name: test-results
          path: test-results/ # Replace with the path to your test results
